name: Deploy application

on:
  push:
    branches:
      - main
    paths:
      - template.yml
      - package.json
      - yarn.lock
      - src/**

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: read

jobs:
  check-project-std:
    uses: ./.github/workflows/check-project-std.yml

  deploy-application:
    runs-on: ubuntu-latest
    needs: [check-project-std]
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::048723829744:role/PRX-GHA-AccessRole
          role-session-name: gha-deploy-health-events-toolkit

      - name: Deploy CloudFormation stack
        run: |
          rm samconfig.toml

          stack_name=health-events-toolkit

          sam build && sam deploy \
            --region us-east-2 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name "$stack_name" \
            --resolve-s3 \
            --no-progressbar \
            --s3-prefix "$stack_name" \
            --capabilities CAPABILITY_IAM \
            --role-arn arn:aws:iam::048723829744:role/PRX-GHA-ServiceRoleForCloudFormation
          aws cloudformation update-termination-protection \
            --stack-name "$stack_name"
            --enable-termination-protection
